// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: controller_message.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_controller_5fmessage_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_controller_5fmessage_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3011000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3011000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_controller_5fmessage_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_controller_5fmessage_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_controller_5fmessage_2eproto;
namespace Controller {
class ControlMsg;
class ControlMsgDefaultTypeInternal;
extern ControlMsgDefaultTypeInternal _ControlMsg_default_instance_;
}  // namespace Controller
PROTOBUF_NAMESPACE_OPEN
template<> ::Controller::ControlMsg* Arena::CreateMaybeMessage<::Controller::ControlMsg>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace Controller {

// ===================================================================

class ControlMsg :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Controller.ControlMsg) */ {
 public:
  ControlMsg();
  virtual ~ControlMsg();

  ControlMsg(const ControlMsg& from);
  ControlMsg(ControlMsg&& from) noexcept
    : ControlMsg() {
    *this = ::std::move(from);
  }

  inline ControlMsg& operator=(const ControlMsg& from) {
    CopyFrom(from);
    return *this;
  }
  inline ControlMsg& operator=(ControlMsg&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const ControlMsg& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const ControlMsg* internal_default_instance() {
    return reinterpret_cast<const ControlMsg*>(
               &_ControlMsg_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(ControlMsg& a, ControlMsg& b) {
    a.Swap(&b);
  }
  inline void Swap(ControlMsg* other) {
    if (other == this) return;
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline ControlMsg* New() const final {
    return CreateMaybeMessage<ControlMsg>(nullptr);
  }

  ControlMsg* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<ControlMsg>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const ControlMsg& from);
  void MergeFrom(const ControlMsg& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(ControlMsg* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Controller.ControlMsg";
  }
  private:
  inline ::PROTOBUF_NAMESPACE_ID::Arena* GetArenaNoVirtual() const {
    return nullptr;
  }
  inline void* MaybeArenaPtr() const {
    return nullptr;
  }
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_controller_5fmessage_2eproto);
    return ::descriptor_table_controller_5fmessage_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kModeFieldNumber = 1,
    kRollFieldNumber = 2,
    kPitchFieldNumber = 3,
    kThrustFieldNumber = 4,
    kYawFieldNumber = 5,
  };
  // int32 mode = 1;
  void clear_mode();
  ::PROTOBUF_NAMESPACE_ID::int32 mode() const;
  void set_mode(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_mode() const;
  void _internal_set_mode(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 roll = 2;
  void clear_roll();
  ::PROTOBUF_NAMESPACE_ID::int32 roll() const;
  void set_roll(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_roll() const;
  void _internal_set_roll(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 pitch = 3;
  void clear_pitch();
  ::PROTOBUF_NAMESPACE_ID::int32 pitch() const;
  void set_pitch(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_pitch() const;
  void _internal_set_pitch(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 thrust = 4;
  void clear_thrust();
  ::PROTOBUF_NAMESPACE_ID::int32 thrust() const;
  void set_thrust(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_thrust() const;
  void _internal_set_thrust(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 yaw = 5;
  void clear_yaw();
  ::PROTOBUF_NAMESPACE_ID::int32 yaw() const;
  void set_yaw(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_yaw() const;
  void _internal_set_yaw(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:Controller.ControlMsg)
 private:
  class _Internal;

  ::PROTOBUF_NAMESPACE_ID::internal::InternalMetadataWithArena _internal_metadata_;
  ::PROTOBUF_NAMESPACE_ID::int32 mode_;
  ::PROTOBUF_NAMESPACE_ID::int32 roll_;
  ::PROTOBUF_NAMESPACE_ID::int32 pitch_;
  ::PROTOBUF_NAMESPACE_ID::int32 thrust_;
  ::PROTOBUF_NAMESPACE_ID::int32 yaw_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_controller_5fmessage_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// ControlMsg

// int32 mode = 1;
inline void ControlMsg::clear_mode() {
  mode_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 ControlMsg::_internal_mode() const {
  return mode_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 ControlMsg::mode() const {
  // @@protoc_insertion_point(field_get:Controller.ControlMsg.mode)
  return _internal_mode();
}
inline void ControlMsg::_internal_set_mode(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  mode_ = value;
}
inline void ControlMsg::set_mode(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_mode(value);
  // @@protoc_insertion_point(field_set:Controller.ControlMsg.mode)
}

// int32 roll = 2;
inline void ControlMsg::clear_roll() {
  roll_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 ControlMsg::_internal_roll() const {
  return roll_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 ControlMsg::roll() const {
  // @@protoc_insertion_point(field_get:Controller.ControlMsg.roll)
  return _internal_roll();
}
inline void ControlMsg::_internal_set_roll(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  roll_ = value;
}
inline void ControlMsg::set_roll(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_roll(value);
  // @@protoc_insertion_point(field_set:Controller.ControlMsg.roll)
}

// int32 pitch = 3;
inline void ControlMsg::clear_pitch() {
  pitch_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 ControlMsg::_internal_pitch() const {
  return pitch_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 ControlMsg::pitch() const {
  // @@protoc_insertion_point(field_get:Controller.ControlMsg.pitch)
  return _internal_pitch();
}
inline void ControlMsg::_internal_set_pitch(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  pitch_ = value;
}
inline void ControlMsg::set_pitch(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_pitch(value);
  // @@protoc_insertion_point(field_set:Controller.ControlMsg.pitch)
}

// int32 thrust = 4;
inline void ControlMsg::clear_thrust() {
  thrust_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 ControlMsg::_internal_thrust() const {
  return thrust_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 ControlMsg::thrust() const {
  // @@protoc_insertion_point(field_get:Controller.ControlMsg.thrust)
  return _internal_thrust();
}
inline void ControlMsg::_internal_set_thrust(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  thrust_ = value;
}
inline void ControlMsg::set_thrust(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_thrust(value);
  // @@protoc_insertion_point(field_set:Controller.ControlMsg.thrust)
}

// int32 yaw = 5;
inline void ControlMsg::clear_yaw() {
  yaw_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 ControlMsg::_internal_yaw() const {
  return yaw_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 ControlMsg::yaw() const {
  // @@protoc_insertion_point(field_get:Controller.ControlMsg.yaw)
  return _internal_yaw();
}
inline void ControlMsg::_internal_set_yaw(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  yaw_ = value;
}
inline void ControlMsg::set_yaw(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_yaw(value);
  // @@protoc_insertion_point(field_set:Controller.ControlMsg.yaw)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace Controller

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_controller_5fmessage_2eproto
